version: "3.5"

services:
  api:
    container_name: go-auth-api
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 5000:5000

  db:
    container_name: go-auth-postgres
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=
    volumes:
      - fibergbdata:/var/lib/postgresql/data

volumes:
  fibergbdata:
